import type { Task, User } from "./database";

type TaskStatus = "pending" | "in_progress" | "completed" | "cancelled";
type TaskPriority = "low" | "medium" | "high";

type SampleAddress = {
  countryCode: string;
  streetName: string;
  houseNumber?: string;
  city: string;
  postalCode: string;
  countrySubdivision: string;
};

type RandomDates = {
  dueDate: Date;
  createdDate: Date;
  updatedDate: Date;
};

type RandomAddress = SampleAddress & {
  addressLine2?: string;
  boxNumber?: string;
};

const TASK_STATUSES: readonly TaskStatus[] = [
  "pending",
  "in_progress",
  "completed",
  "cancelled",
];

const TASK_PRIORITIES: readonly TaskPriority[] = ["low", "medium", "high"];

const SAMPLE_ADDRESSES: readonly SampleAddress[] = [
  {
    countryCode: "US",
    streetName: "Main Street",
    houseNumber: "123",
    postalCode: "10001",
    city: "New York",
    countrySubdivision: "New York",
  },
  {
    countryCode: "US",
    streetName: "Oak Avenue",
    houseNumber: "456",
    postalCode: "90001",
    city: "Los Angeles",
    countrySubdivision: "California",
  },
  {
    countryCode: "US",
    streetName: "Pine Road",
    houseNumber: "789",
    postalCode: "60601",
    city: "Chicago",
    countrySubdivision: "Illinois",
  },
  {
    countryCode: "GB",
    streetName: "Downing Street",
    houseNumber: "10",
    postalCode: "SW1A 2AA",
    city: "London",
    countrySubdivision: "England",
  },
  {
    countryCode: "GB",
    streetName: "Baker Street",
    houseNumber: "221B",
    postalCode: "NW1 6XE",
    city: "London",
    countrySubdivision: "England",
  },
  {
    countryCode: "FR",
    streetName: "Avenue des Champs-Élysées",
    houseNumber: "1",
    postalCode: "75008",
    city: "Paris",
    countrySubdivision: "Île-de-France",
  },
  {
    countryCode: "FR",
    streetName: "Rue de la Paix",
    houseNumber: "5",
    postalCode: "75002",
    city: "Paris",
    countrySubdivision: "Île-de-France",
  },
  {
    countryCode: "DE",
    streetName: "Brandenburger Tor",
    postalCode: "10117",
    city: "Berlin",
    countrySubdivision: "Berlin",
  },
  {
    countryCode: "DE",
    streetName: "Marienplatz",
    houseNumber: "1",
    postalCode: "80331",
    city: "Munich",
    countrySubdivision: "Bavaria",
  },
  {
    countryCode: "CA",
    streetName: "Wellington Street",
    houseNumber: "100",
    postalCode: "K1A 0A9",
    city: "Ottawa",
    countrySubdivision: "Ontario",
  },
  {
    countryCode: "CA",
    streetName: "Front Street",
    houseNumber: "301",
    postalCode: "M5V 2T6",
    city: "Toronto",
    countrySubdivision: "Ontario",
  },
  {
    countryCode: "AU",
    streetName: "Macquarie Street",
    houseNumber: "1",
    postalCode: "2000",
    city: "Sydney",
    countrySubdivision: "New South Wales",
  },
  {
    countryCode: "AU",
    streetName: "Collins Street",
    houseNumber: "100",
    postalCode: "3000",
    city: "Melbourne",
    countrySubdivision: "Victoria",
  },
  {
    countryCode: "JP",
    streetName: "Chiyoda",
    houseNumber: "1-1",
    postalCode: "100-0001",
    city: "Tokyo",
    countrySubdivision: "Tokyo",
  },
  {
    countryCode: "JP",
    streetName: "Umeda",
    houseNumber: "1-1",
    postalCode: "530-0001",
    city: "Osaka",
    countrySubdivision: "Osaka",
  },
  {
    countryCode: "IT",
    streetName: "Via del Corso",
    houseNumber: "1",
    postalCode: "00186",
    city: "Rome",
    countrySubdivision: "Lazio",
  },
  {
    countryCode: "IT",
    streetName: "Piazza del Duomo",
    postalCode: "20122",
    city: "Milan",
    countrySubdivision: "Lombardy",
  },
  {
    countryCode: "ES",
    streetName: "Gran Vía",
    houseNumber: "1",
    postalCode: "28013",
    city: "Madrid",
    countrySubdivision: "Madrid",
  },
  {
    countryCode: "ES",
    streetName: "La Rambla",
    houseNumber: "1",
    postalCode: "08002",
    city: "Barcelona",
    countrySubdivision: "Catalonia",
  },
  {
    countryCode: "NL",
    streetName: "Dam Square",
    houseNumber: "1",
    postalCode: "1012 JS",
    city: "Amsterdam",
    countrySubdivision: "North Holland",
  },
];

const RANDOM_NAMES: readonly string[] = [
  "John Doe",
  "Jane Doe",
  "Alice Smith",
  "Bob Brown",
  "Charlie Green",
  "Diana Prince",
  "Clark Kent",
  "Bruce Wayne",
  "Selina Kyle",
  "Barry Allen",
  "Iris West",
  "Arthur Curry",
  "Mera",
  "Victor Stone",
  "Silas Stone",
  "Hal Jordan",
  "Carol Danvers",
  "Tony Stark",
  "Steve Rogers",
  "Natasha Romanoff",
  "Thor Odinson",
  "Bruce Banner",
  "Peter Parker",
  "Wanda Maximoff",
  "Vision",
  "Sam Wilson",
  "Bucky Barnes",
  "Scott Lang",
  "Hope van Dyne",
  "T'Challa",
  "Shuri",
  "Okoye",
  "Nakia",
  "M'Baku",
  "Killmonger",
  "Erik Stevens",
  "N'Jadaka",
  "Zemo",
  "Red Skull",
  "Loki",
  "Hela",
  "Surtur",
  "Malekith",
  "Kurse",
  "Ronan",
  "Thanos",
  "Gamora",
  "Nebula",
  "Drax",
  "Rocket",
  "Groot",
  "Mantis",
  "Yondu",
  "Ego",
  "Ayesha",
  "Taserface",
  "Kraglin",
  "Howard the Duck",
  "Cosmo",
  "Adam Warlock",
  "Phyla-Vell",
  "Moondragon",
  "Nova",
  "Quasar",
  "Photon",
  "Monica Rambeau",
  "Maria Rambeau",
  "Carol Danvers",
  "Nick Fury",
  "Maria Hill",
  "Phil Coulson",
  "Melinda May",
  "Daisy Johnson",
  "Leo Fitz",
  "Jemma Simmons",
  "Mack",
  "Yo-Yo",
  "Deke Shaw",
  "Enoch",
  "Flint",
  "Tess",
  "Gordon",
  "Lincoln Campbell",
  "Hive",
  "Ward",
  "Garrett",
  "Whitehall",
  "Cal",
  "Jiaying",
  "Gordon",
  "Flint",
  "Tess",
  "Lincoln Campbell",
  "Hive",
  "Ward",
  "Garrett",
  "Whitehall",
  "Cal",
  "Jiaying",
  "Gordon",
  "Flint",
  "Tess",
  "Lincoln Campbell",
  "Hive",
  "Ward",
  "Garrett",
  "Whitehall",
];

const RANDOM_TASK_NAMES: readonly string[] = [
  "Review code changes",
  "Update documentation",
  "Fix bug in login system",
  "Implement new feature",
  "Write unit tests",
  "Deploy to staging",
  "Code review",
  "Database optimization",
  "API integration",
  "UI/UX improvements",
  "Performance optimization",
  "Security audit",
  "Backup verification",
  "System monitoring",
  "User training",
  "Requirements gathering",
  "Design review",
  "Testing phase",
  "Bug triage",
  "Release planning",
  "Sprint planning",
  "Retrospective meeting",
  "Stakeholder meeting",
  "Technical debt cleanup",
  "Dependency updates",
  "Configuration management",
  "Log analysis",
  "Error tracking",
  "Metrics collection",
  "Alert setup",
  "Incident response",
  "Disaster recovery",
  "Capacity planning",
  "Load testing",
  "Stress testing",
  "Integration testing",
  "End-to-end testing",
  "User acceptance testing",
  "Regression testing",
  "Smoke testing",
  "Sanity testing",
  "Exploratory testing",
  "Automation framework",
  "CI/CD pipeline",
  "Build optimization",
  "Deployment automation",
  "Infrastructure as code",
  "Container orchestration",
  "Microservices architecture",
  "API gateway",
  "Service mesh",
  "Load balancer",
  "Database sharding",
  "Caching strategy",
  "CDN configuration",
  "SSL certificate renewal",
  "Domain management",
  "DNS configuration",
  "Email setup",
  "Monitoring dashboard",
  "Alerting rules",
  "Log aggregation",
  "Metrics visualization",
  "Performance profiling",
  "Memory optimization",
  "CPU optimization",
  "Network optimization",
  "Storage optimization",
  "Backup strategy",
  "Recovery procedures",
  "Compliance audit",
  "Security scanning",
  "Vulnerability assessment",
  "Penetration testing",
  "Code signing",
  "Package management",
  "Version control",
  "Branch strategy",
  "Merge conflict resolution",
  "Code formatting",
  "Linting rules",
  "Static analysis",
  "Dynamic analysis",
  "Code coverage",
  "Mutation testing",
  "Property-based testing",
  "Contract testing",
  "Consumer-driven contracts",
  "API versioning",
  "Backward compatibility",
  "Feature flags",
  "A/B testing",
  "Canary deployments",
  "Blue-green deployments",
  "Rollback procedures",
  "Hotfix process",
  "Release notes",
  "Changelog maintenance",
  "Documentation updates",
  "Knowledge base",
  "FAQ updates",
  "User guide",
  "Admin guide",
  "Developer guide",
  "API documentation",
  "SDK documentation",
  "Plugin development",
  "Extension development",
  "Custom integrations",
  "Third-party services",
  "Payment processing",
  "Authentication service",
  "Authorization service",
  "Single sign-on",
  "Multi-factor authentication",
  "Password policies",
  "Session management",
  "Token management",
  "OAuth implementation",
  "JWT handling",
  "API rate limiting",
  "Throttling",
  "Quotas",
  "Usage tracking",
  "Analytics implementation",
  "Event tracking",
  "Conversion tracking",
  "Funnel analysis",
  "Cohort analysis",
  "Retention analysis",
  "Churn analysis",
  "Customer segmentation",
  "Personalization",
  "Recommendation engine",
  "Search optimization",
  "SEO implementation",
  "Sitemap generation",
  "Robots.txt",
  "Meta tags",
  "Schema markup",
  "Open Graph",
  "Twitter Cards",
  "Social media integration",
  "Email marketing",
  "Newsletter system",
  "Notification system",
  "Push notifications",
  "SMS integration",
  "WhatsApp integration",
  "Slack integration",
  "Discord integration",
  "Teams integration",
  "Zoom integration",
  "Calendar integration",
  "Gmail integration",
  "Outlook integration",
  "CRM integration",
  "ERP integration",
  "Accounting integration",
  "Inventory management",
  "Order processing",
  "Shipping integration",
  "Tracking system",
  "Returns processing",
  "Refund processing",
  "Dispute resolution",
  "Customer support",
  "Ticket system",
  "Live chat",
  "FAQ system",
  "Knowledge base",
  "Video tutorials",
  "Screencasts",
  "Webinars",
  "Training materials",
  "Certification program",
  "Onboarding process",
  "Offboarding process",
  "Employee management",
  "Time tracking",
  "Project management",
  "Task management",
  "Issue tracking",
  "Bug tracking",
  "Feature requests",
  "Roadmap planning",
  "Product strategy",
  "Market research",
  "Competitive analysis",
  "User research",
  "Usability testing",
  "Accessibility audit",
  "WCAG compliance",
  "GDPR compliance",
  "CCPA compliance",
  "HIPAA compliance",
  "SOX compliance",
  "PCI DSS compliance",
  "ISO 27001",
  "SOC 2",
  "Penetration testing",
  "Vulnerability assessment",
  "Security audit",
  "Risk assessment",
  "Business continuity",
  "Disaster recovery",
  "Incident response",
  "Forensic analysis",
  "Malware analysis",
  "Threat intelligence",
  "Security monitoring",
  "SIEM implementation",
  "EDR deployment",
  "Firewall configuration",
  "VPN setup",
  "Network segmentation",
  "Access control",
  "Identity management",
  "Privileged access management",
  "Secrets management",
  "Key management",
  "Certificate management",
  "PKI implementation",
  "Digital signatures",
  "Encryption at rest",
  "Encryption in transit",
  "Data classification",
  "Data retention",
  "Data archival",
  "Data backup",
  "Data recovery",
  "Data migration",
  "Data transformation",
  "ETL processes",
  "Data warehousing",
  "Business intelligence",
  "Reporting system",
  "Dashboard creation",
  "KPI tracking",
  "Metrics collection",
  "Performance monitoring",
  "Application monitoring",
  "Infrastructure monitoring",
  "Network monitoring",
  "Database monitoring",
  "Server monitoring",
  "Cloud monitoring",
  "Cost optimization",
  "Resource management",
  "Capacity planning",
  "Scaling strategy",
  "Auto-scaling",
  "Load balancing",
  "High availability",
  "Fault tolerance",
  "Redundancy",
  "Failover",
  "Backup systems",
  "Recovery systems",
  "Disaster recovery",
  "Business continuity",
  "Change management",
  "Release management",
  "Deployment strategy",
  "Rollback strategy",
  "Feature flags",
  "A/B testing",
  "Canary releases",
  "Blue-green deployment",
  "Zero-downtime deployment",
  "Continuous deployment",
  "Continuous integration",
  "Automated testing",
  "Test automation",
  "CI/CD pipeline",
  "Build automation",
  "Deployment automation",
  "Infrastructure automation",
  "Configuration management",
  "Orchestration",
  "Containerization",
  "Virtualization",
  "Cloud migration",
  "Hybrid cloud",
  "Multi-cloud",
  "Edge computing",
  "IoT integration",
  "Mobile development",
  "Web development",
  "Desktop development",
  "API development",
  "Microservices",
  "Monolith",
  "Serverless",
  "Functions as a Service",
  "Platform as a Service",
  "Infrastructure as a Service",
  "Software as a Service",
  "Backend as a Service",
  "Database as a Service",
];

const RANDOM_DESCRIPTIONS: readonly string[] = [
  "This task involves reviewing and analyzing code changes for quality and adherence to standards.",
  "Updating project documentation to reflect current state and recent changes.",
  "Investigating and fixing a critical bug in the user authentication system.",
  "Implementing a new feature based on user requirements and specifications.",
  "Creating comprehensive unit tests to ensure code reliability and maintainability.",
  "Deploying the application to the staging environment for testing.",
  "Performing thorough code review to ensure code quality and best practices.",
  "Optimizing database queries and structure for better performance.",
  "Integrating with external APIs to extend application functionality.",
  "Improving user interface and user experience based on feedback.",
  "Optimizing application performance through various techniques.",
  "Conducting security audit to identify and fix vulnerabilities.",
  "Verifying backup systems and data integrity.",
  "Setting up system monitoring and alerting mechanisms.",
  "Conducting user training sessions for new features.",
  "Gathering and analyzing user requirements for new features.",
  "Reviewing design specifications and mockups.",
  "Executing comprehensive testing procedures.",
  "Prioritizing and categorizing reported bugs.",
  "Planning and coordinating software releases.",
  "Planning development sprints and allocating resources.",
  "Conducting retrospective meetings to improve processes.",
  "Meeting with stakeholders to discuss project progress.",
  "Addressing technical debt to improve code maintainability.",
  "Updating project dependencies to latest stable versions.",
  "Managing configuration files and environment settings.",
  "Analyzing application logs for debugging and optimization.",
  "Setting up error tracking and monitoring systems.",
  "Implementing metrics collection for performance analysis.",
  "Configuring alert systems for critical issues.",
  "Developing incident response procedures and protocols.",
  "Creating disaster recovery plans and procedures.",
  "Planning system capacity and resource allocation.",
  "Performing load testing to ensure system stability.",
  "Conducting stress testing to identify breaking points.",
  "Executing integration testing between components.",
  "Performing end-to-end testing of complete workflows.",
  "Conducting user acceptance testing with stakeholders.",
  "Running regression tests to ensure no new issues.",
  "Performing smoke tests for critical functionality.",
  "Conducting sanity tests for basic functionality.",
  "Performing exploratory testing to find edge cases.",
  "Building automation framework for testing.",
  "Setting up continuous integration and deployment pipeline.",
  "Optimizing build processes for faster compilation.",
  "Automating deployment procedures for consistency.",
  "Implementing infrastructure as code practices.",
  "Setting up container orchestration for scalability.",
  "Designing microservices architecture for modularity.",
  "Implementing API gateway for centralized access.",
  "Deploying service mesh for inter-service communication.",
  "Configuring load balancer for traffic distribution.",
  "Implementing database sharding for horizontal scaling.",
  "Developing caching strategy for performance improvement.",
  "Configuring CDN for content delivery optimization.",
  "Renewing SSL certificates for secure communication.",
  "Managing domain names and DNS configuration.",
  "Setting up email services and configuration.",
  "Creating monitoring dashboards for system visibility.",
  "Defining alerting rules for proactive monitoring.",
  "Implementing log aggregation for centralized logging.",
  "Setting up metrics visualization for data analysis.",
  "Performing performance profiling for optimization.",
  "Optimizing memory usage for better performance.",
  "Optimizing CPU usage for efficiency.",
  "Optimizing network configuration for speed.",
  "Optimizing storage usage and performance.",
  "Developing comprehensive backup strategies.",
  "Creating recovery procedures for data restoration.",
  "Conducting compliance audits for regulatory requirements.",
  "Performing security scanning for vulnerabilities.",
  "Conducting vulnerability assessments for risk analysis.",
  "Performing penetration testing for security validation.",
  "Implementing code signing for authenticity verification.",
  "Managing package dependencies and versions.",
  "Setting up version control systems and workflows.",
  "Defining branch strategies for code management.",
  "Resolving merge conflicts in collaborative development.",
  "Implementing code formatting standards.",
  "Setting up linting rules for code quality.",
  "Performing static analysis for code review.",
  "Conducting dynamic analysis for runtime behavior.",
  "Measuring code coverage for testing completeness.",
  "Performing mutation testing for test quality.",
  "Implementing property-based testing for edge cases.",
  "Setting up contract testing for service integration.",
  "Implementing consumer-driven contracts for API design.",
  "Managing API versioning for backward compatibility.",
  "Ensuring backward compatibility for existing clients.",
  "Implementing feature flags for controlled rollouts.",
  "Setting up A/B testing for feature validation.",
  "Implementing canary deployments for risk mitigation.",
  "Setting up blue-green deployments for zero downtime.",
  "Creating rollback procedures for emergency situations.",
  "Establishing hotfix process for critical issues.",
  "Writing release notes for version documentation.",
  "Maintaining changelog for version history.",
  "Updating documentation for current features.",
  "Building knowledge base for user support.",
  "Updating FAQ with common questions.",
  "Creating user guide for application usage.",
  "Developing admin guide for system management.",
  "Writing developer guide for technical users.",
  "Creating API documentation for integration.",
  "Developing SDK documentation for developers.",
  "Building plugin development framework.",
  "Creating extension development platform.",
  "Implementing custom integrations for third-party services.",
  "Integrating payment processing systems.",
  "Setting up authentication service for user management.",
  "Implementing authorization service for access control.",
  "Configuring single sign-on for user convenience.",
  "Setting up multi-factor authentication for security.",
  "Defining password policies for account security.",
  "Implementing session management for user sessions.",
  "Managing token lifecycle for API access.",
  "Implementing OAuth for third-party authentication.",
  "Handling JWT tokens for stateless authentication.",
  "Implementing API rate limiting for abuse prevention.",
  "Setting up throttling for resource protection.",
  "Defining usage quotas for fair resource allocation.",
  "Implementing usage tracking for analytics.",
  "Setting up analytics implementation for insights.",
  "Implementing event tracking for user behavior.",
  "Setting up conversion tracking for business metrics.",
  "Implementing funnel analysis for user journey.",
  "Conducting cohort analysis for user retention.",
  "Analyzing retention patterns for user engagement.",
  "Performing churn analysis for user loss prevention.",
  "Implementing customer segmentation for targeting.",
  "Developing personalization features for user experience.",
  "Building recommendation engine for content discovery.",
  "Optimizing search functionality for better results.",
  "Implementing SEO best practices for visibility.",
  "Generating sitemap for search engine indexing.",
  "Configuring robots.txt for web crawlers.",
  "Implementing meta tags for social sharing.",
  "Adding schema markup for rich snippets.",
  "Configuring Open Graph for social media.",
  "Setting up Twitter Cards for social sharing.",
  "Integrating social media platforms for engagement.",
  "Setting up email marketing campaigns.",
  "Implementing newsletter system for communication.",
  "Building notification system for user alerts.",
  "Setting up push notifications for mobile engagement.",
  "Integrating SMS services for text notifications.",
  "Connecting WhatsApp Business API for messaging.",
  "Integrating Slack for team communication.",
  "Connecting Discord for community engagement.",
  "Integrating Microsoft Teams for collaboration.",
  "Connecting Zoom for video conferencing.",
  "Integrating calendar systems for scheduling.",
  "Connecting Gmail for email integration.",
  "Integrating Outlook for email management.",
  "Connecting CRM systems for customer management.",
  "Integrating ERP systems for business processes.",
  "Connecting accounting software for financial management.",
  "Implementing inventory management system.",
  "Setting up order processing workflow.",
  "Integrating shipping services for delivery.",
  "Building tracking system for order status.",
  "Implementing returns processing for customer service.",
  "Setting up refund processing for financial transactions.",
  "Creating dispute resolution system for conflicts.",
  "Building customer support system for assistance.",
  "Implementing ticket system for issue tracking.",
  "Setting up live chat for real-time support.",
  "Building FAQ system for self-service support.",
  "Creating knowledge base for documentation.",
  "Developing video tutorials for user education.",
  "Creating screencasts for feature demonstrations.",
  "Organizing webinars for user training.",
  "Developing training materials for onboarding.",
  "Creating certification program for skill validation.",
  "Designing onboarding process for new users.",
  "Establishing offboarding process for departing users.",
  "Implementing employee management system.",
  "Setting up time tracking for productivity measurement.",
  "Building project management system for coordination.",
  "Implementing task management for workflow.",
  "Setting up issue tracking for problem management.",
  "Building bug tracking system for quality assurance.",
  "Implementing feature request system for product development.",
  "Creating roadmap planning for product strategy.",
  "Developing product strategy for business growth.",
  "Conducting market research for competitive analysis.",
  "Performing competitive analysis for market positioning.",
  "Conducting user research for product development.",
  "Performing usability testing for user experience.",
  "Conducting accessibility audit for inclusive design.",
  "Ensuring WCAG compliance for accessibility standards.",
  "Implementing GDPR compliance for data protection.",
  "Ensuring CCPA compliance for privacy regulations.",
  "Maintaining HIPAA compliance for healthcare data.",
  "Ensuring SOX compliance for financial reporting.",
  "Implementing PCI DSS compliance for payment security.",
  "Achieving ISO 27001 certification for information security.",
  "Obtaining SOC 2 certification for security controls.",
  "Conducting penetration testing for security validation.",
  "Performing vulnerability assessment for risk management.",
  "Conducting security audit for compliance verification.",
  "Performing risk assessment for threat analysis.",
  "Developing business continuity plan for disaster recovery.",
  "Creating disaster recovery plan for system restoration.",
  "Establishing incident response procedures for emergencies.",
  "Performing forensic analysis for security investigations.",
  "Conducting malware analysis for threat intelligence.",
  "Implementing threat intelligence for security awareness.",
  "Setting up security monitoring for threat detection.",
  "Implementing SIEM for security event management.",
  "Deploying EDR for endpoint detection and response.",
  "Configuring firewall for network security.",
  "Setting up VPN for secure remote access.",
  "Implementing network segmentation for security.",
  "Setting up access control for resource protection.",
  "Implementing identity management for user authentication.",
  "Setting up privileged access management for security.",
  "Implementing secrets management for credential protection.",
  "Setting up key management for cryptographic operations.",
  "Implementing certificate management for SSL/TLS.",
  "Setting up PKI for digital certificate infrastructure.",
  "Implementing digital signatures for document authentication.",
  "Implementing encryption at rest for data protection.",
  "Implementing encryption in transit for secure communication.",
  "Implementing data classification for information management.",
  "Setting up data retention policies for compliance.",
  "Implementing data archival for long-term storage.",
  "Setting up data backup for disaster recovery.",
  "Implementing data recovery procedures for restoration.",
  "Performing data migration for system upgrades.",
  "Implementing data transformation for format conversion.",
  "Setting up ETL processes for data integration.",
  "Implementing data warehousing for analytics.",
  "Building business intelligence system for insights.",
  "Implementing reporting system for data analysis.",
  "Creating dashboards for data visualization.",
  "Setting up KPI tracking for performance measurement.",
  "Implementing metrics collection for monitoring.",
  "Setting up performance monitoring for optimization.",
  "Implementing application monitoring for reliability.",
  "Setting up infrastructure monitoring for system health.",
  "Implementing network monitoring for connectivity.",
  "Setting up database monitoring for performance.",
  "Implementing server monitoring for resource usage.",
  "Setting up cloud monitoring for cloud resources.",
  "Implementing cost optimization for resource efficiency.",
  "Setting up resource management for allocation.",
  "Implementing capacity planning for scalability.",
  "Developing scaling strategy for growth.",
  "Implementing auto-scaling for dynamic workloads.",
  "Setting up load balancing for traffic distribution.",
  "Implementing high availability for reliability.",
  "Setting up fault tolerance for resilience.",
  "Implementing redundancy for backup systems.",
  "Setting up failover for automatic recovery.",
  "Implementing backup systems for data protection.",
  "Setting up recovery systems for restoration.",
  "Implementing disaster recovery for business continuity.",
  "Setting up business continuity for operations.",
  "Implementing change management for controlled updates.",
  "Setting up release management for version control.",
  "Developing deployment strategy for rollouts.",
  "Implementing rollback strategy for emergency recovery.",
  "Setting up feature flags for controlled releases.",
  "Implementing A/B testing for feature validation.",
  "Setting up canary releases for risk mitigation.",
  "Implementing blue-green deployment for zero downtime.",
  "Setting up zero-downtime deployment for continuous service.",
  "Implementing continuous deployment for automation.",
  "Setting up continuous integration for code quality.",
  "Implementing automated testing for reliability.",
  "Setting up test automation for efficiency.",
  "Implementing CI/CD pipeline for automation.",
  "Setting up build automation for consistency.",
  "Implementing deployment automation for efficiency.",
  "Setting up infrastructure automation for scalability.",
  "Implementing configuration management for consistency.",
  "Setting up orchestration for service coordination.",
  "Implementing containerization for portability.",
  "Setting up virtualization for resource optimization.",
  "Implementing cloud migration for scalability.",
  "Setting up hybrid cloud for flexibility.",
  "Implementing multi-cloud for redundancy.",
  "Setting up edge computing for low latency.",
  "Implementing IoT integration for connected devices.",
  "Developing mobile applications for mobile users.",
  "Developing web applications for browser users.",
  "Developing desktop applications for local users.",
  "Developing APIs for service integration.",
  "Implementing microservices for modularity.",
  "Maintaining monolith architecture for simplicity.",
  "Implementing serverless for scalability.",
  "Setting up Functions as a Service for event-driven computing.",
  "Implementing Platform as a Service for development.",
  "Setting up Infrastructure as a Service for flexibility.",
  "Implementing Software as a Service for accessibility.",
  "Setting up Backend as a Service for rapid development.",
  "Implementing Database as a Service for managed databases.",
];

const generateEmailFromName = (name: string): string => {
  return `${name
    .toLowerCase()
    .replace(/\s+/g, ".")
    .replace(/[^a-z0-9.]/g, "")}@example.com`;
};

const pickRandom = <T>(arr: readonly T[]): T => {
  return arr[Math.floor(Math.random() * arr.length)];
};

const buildRandomDates = (): RandomDates => {
  const dueDays = Math.floor(Math.random() * 30);
  const createdDays = Math.floor(Math.random() * 90);
  const updatedDays = Math.floor(Math.random() * (90 - createdDays));
  const createdDate = new Date(Date.now() - createdDays * 86400000);
  return {
    dueDate: new Date(Date.now() + dueDays * 86400000),
    createdDate,
    updatedDate: new Date(createdDate.getTime() + updatedDays * 86400000),
  };
};

const buildRandomAddress = (): RandomAddress | undefined => {
  const hasAddress = Math.random() < 0.7;
  if (!hasAddress) return undefined;
  const base = pickRandom(SAMPLE_ADDRESSES);
  const includeOptional = Math.random() < 0.3;
  return {
    ...base,
    ...(includeOptional && {
      addressLine2: `Suite ${Math.floor(Math.random() * 500) + 1}`,
    }),
  };
};

const buildRandomTask = (i: number): Partial<Task> => {
  const ownerName = pickRandom(RANDOM_NAMES);
  const taskName = pickRandom(RANDOM_TASK_NAMES);
  const dates = buildRandomDates();
  return {
    _id: i.toString(),
    name: taskName,
    owner: ownerName,
    email: generateEmailFromName(ownerName),
    status: pickRandom(TASK_STATUSES),
    priority: pickRandom(TASK_PRIORITIES),
    description: pickRandom(RANDOM_DESCRIPTIONS),
    due_date: dates.dueDate,
    assignees: pickRandomUser()._id,
    price: Math.floor(Math.random() * 1000) + 1,
    completion_percentage: Math.random(),
    url: `https://www.google.com/search?q=${taskName}`,
    phone: "+1-555-123-4567",
    done: false,
    address: buildRandomAddress(),
    isArchived: i > 700 && i <= 710,
    createdAt: dates.createdDate,
    updatedAt: dates.updatedDate,
  };
};

const generateRandomTasks = (count: number): Partial<Task>[] => {
  const tasks: Partial<Task>[] = [];
  for (let i = 16; i <= count + 15; i++) {
    tasks.push(buildRandomTask(i));
  }
  return tasks;
};

function pickRandomUser(): User {
  return defaultUsers[Math.floor(Math.random() * defaultUsers.length)];
}

export const defaultUsers: User[] = [
  {
    _id: "1",
    name: "John Doe",
    email: "john.doe@example.com",
    phone: "+1-555-123-4567",
    avatar: "https://dummyjson.com/image/150",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "2",
    name: "Jane Doe",
    email: "jane.doe@example.com",
    phone: "+1-555-123-4568",
    avatar: "https://dummyjson.com/image/150",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "3",
    name: "John Doe",
    email: "john.doe@example.com",
    phone: "+1-555-123-4569",
    avatar: "https://dummyjson.com/image/150",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "4",
    name: "Jane Doe",
    email: "jane.doe@example.com",
    phone: "+1-555-123-4570",
    avatar: "https://dummyjson.com/image/150",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "5",
    name: "John Doe",
    email: "john.doe@example.com",
    phone: "+1-555-123-4571",
    avatar: "https://dummyjson.com/image/150",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "6",
    name: "Jane Doe",
    email: "jane.doe@example.com",
    phone: "+1-555-123-4572",
    avatar: "https://dummyjson.com/image/150",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "7",
    name: "John Doe",
    email: "john.doe@example.com",
    phone: "+1-555-123-4573",
    avatar: "https://dummyjson.com/image/150",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "8",
    name: "Jane Doe",
    email: "jane.doe@example.com",
    phone: "+1-555-123-4574",
    avatar: "https://dummyjson.com/image/150",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "9",
    name: "John Doe",
    email: "john.doe@example.com",
    phone: "+1-555-123-4575",
    avatar: "https://dummyjson.com/image/150",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "10",
    name: "Jane Doe",
    email: "jane.doe@example.com",
    phone: "+1-555-123-4576",
    avatar: "https://dummyjson.com/image/150",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "11",
    name: "John Doe",
    email: "john.doe@example.com",
    phone: "+1-555-123-4577",
    avatar: "https://dummyjson.com/image/150",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "12",
    name: "Jane Doe",
    email: "jane.doe@example.com",
    phone: "+1-555-123-4578",
    avatar: "https://dummyjson.com/image/150",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "13",
    name: "John Doe",
    email: "john.doe@example.com",
    phone: "+1-555-123-4579",
    avatar: "https://dummyjson.com/image/150",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "14",
    name: "Jane Doe",
    email: "jane.doe@example.com",
    phone: "+1-555-123-4580",
    avatar: "https://dummyjson.com/image/150",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "15",
    name: "John Doe",
    email: "john.doe@example.com",
    phone: "+1-555-123-4581",
    avatar: "https://dummyjson.com/image/150",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const defaultTasks: Partial<Task>[] = [
  {
    _id: "1",
    name: "Task 1",
    owner: "John Doe",
    email: "john.doe@example.com",
    status: "pending",
    priority: "low",
    description: "Task 1 description",
    due_date: new Date(),
    assignees: pickRandomUser()._id,
    price: 100,
    completion_percentage: 0.15,
    url: "https://www.google.com/search?q=Task+1",
    done: false,
    phone: "+1-555-123-4582",
    address: {
      countryCode: "US",
      streetName: "Main Street",
      houseNumber: "123",
      addressLine2: "Suite 100",
      postalCode: "10001",
      city: "New York",
      countrySubdivision: "New York",
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "2",
    name: "Task 2",
    owner: "Jane Doe",
    email: "jane.doe@example.com",
    status: "in_progress",
    priority: "medium",
    description: "Task 2 description",
    due_date: new Date(Date.now() + 86400000),
    assignees: pickRandomUser()._id,
    price: 200,
    completion_percentage: 0.65,
    url: "https://www.google.com/search?q=Task+2",
    done: false,
    phone: "+1-555-123-4582",
    address: {
      countryCode: "GB",
      streetName: "Downing Street",
      houseNumber: "10",
      postalCode: "SW1A 2AA",
      city: "London",
      countrySubdivision: "England",
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "3",
    name: "Task 3",
    owner: "Alice Smith",
    email: "alice.smith@example.com",
    status: "completed",
    priority: "high",
    description: "Task 3 description",
    due_date: new Date(Date.now() + 2 * 86400000),
    assignees: pickRandomUser()._id,
    price: 300,
    completion_percentage: 1.0,
    url: "https://www.google.com/search?q=Task+3",
    done: false,
    phone: "+1-555-123-4582",
    address: {
      countryCode: "FR",
      streetName: "Avenue des Champs-Élysées",
      houseNumber: "1",
      postalCode: "75008",
      city: "Paris",
      countrySubdivision: "Île-de-France",
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "4",
    name: "Task 4",
    owner: "Bob Brown",
    email: "bob.brown@example.com",
    status: "cancelled",
    priority: "low",
    description: "Task 4 description",
    due_date: new Date(Date.now() + 3 * 86400000),
    assignees: pickRandomUser()._id,
    price: 400,
    completion_percentage: 0.25,
    url: "https://www.google.com/search?q=Task+4",
    done: false,
    phone: "+1-555-123-4582",
    address: {
      countryCode: "DE",
      streetName: "Brandenburger Tor",
      addressLine2: "Pariser Platz",
      postalCode: "10117",
      city: "Berlin",
      countrySubdivision: "Berlin",
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "5",
    name: "Task 5",
    owner: "Charlie Green",
    email: "charlie.green@example.com",
    status: "pending",
    priority: "medium",
    description: "Task 5 description",
    due_date: new Date(Date.now() + 4 * 86400000),
    assignees: pickRandomUser()._id,
    price: 500,
    completion_percentage: 0.0,
    url: "https://www.google.com/search?q=Task+5",
    done: false,
    phone: "+1-555-123-4582",
    address: {
      countryCode: "CA",
      streetName: "Wellington Street",
      houseNumber: "100",
      postalCode: "K1A 0A9",
      city: "Ottawa",
      countrySubdivision: "Ontario",
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "6",
    name: "Task 6",
    owner: "Diana Prince",
    email: "diana.prince@example.com",
    status: "in_progress",
    priority: "high",
    description: "Task 6 description",
    due_date: new Date(Date.now() + 5 * 86400000),
    assignees: pickRandomUser()._id,
    price: 600,
    completion_percentage: 0.85,
    url: "https://www.google.com/search?q=Task+6",
    done: false,
    phone: "+1-555-123-4582",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "7",
    name: "Task 7",
    owner: "Clark Kent",
    email: "clark.kent@example.com",
    status: "completed",
    priority: "medium",
    description: "Task 7 description",
    due_date: new Date(Date.now() + 6 * 86400000),
    assignees: pickRandomUser()._id,
    price: 700,
    completion_percentage: 1.0,
    url: "https://www.google.com/search?q=Task+7",
    done: false,
    phone: "+1-555-123-4582",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "8",
    name: "Task 8",
    owner: "Bruce Wayne",
    email: "bruce.wayne@example.com",
    status: "pending",
    priority: "low",
    description: "Task 8 description",
    due_date: new Date(Date.now() + 7 * 86400000),
    assignees: pickRandomUser()._id,
    price: 800,
    completion_percentage: 0.0,
    url: "https://www.google.com/search?q=Task+8",
    done: false,
    phone: "+1-555-123-4582",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "9",
    name: "Task 9",
    owner: "Selina Kyle",
    email: "selina.kyle@example.com",
    status: "cancelled",
    priority: "high",
    description: "Task 9 description",
    due_date: new Date(Date.now() + 8 * 86400000),
    assignees: pickRandomUser()._id,
    price: 900,
    completion_percentage: 0.45,
    url: "https://www.google.com/search?q=Task+9",
    done: false,
    phone: "+1-555-123-4582",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "10",
    name: "Task 10",
    owner: "Barry Allen",
    email: "barry.allen@example.com",
    status: "in_progress",
    priority: "medium",
    description: "Task 10 description",
    due_date: new Date(Date.now() + 9 * 86400000),
    assignees: pickRandomUser()._id,
    price: 1000,
    completion_percentage: 0.75,
    url: "https://www.google.com/search?q=Task+10",
    done: false,
    phone: "+1-555-123-4582",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "11",
    name: "Task 11",
    owner: "Iris West",
    email: "iris.west@example.com",
    status: "completed",
    priority: "low",
    description: "Task 11 description",
    due_date: new Date(Date.now() + 10 * 86400000),
    assignees: pickRandomUser()._id,
    price: 1100,
    completion_percentage: 1.0,
    url: "https://www.google.com/search?q=Task+11",
    done: false,
    phone: "+1-555-123-4582",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "12",
    name: "Task 12",
    owner: "Arthur Curry",
    email: "arthur.curry@example.com",
    status: "pending",
    priority: "high",
    description: "Task 12 description",
    due_date: new Date(Date.now() + 11 * 86400000),
    assignees: pickRandomUser()._id,
    price: 1200,
    completion_percentage: 0.05,
    url: "https://www.google.com/search?q=Task+12",
    done: false,
    phone: "+1-555-123-4582",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "13",
    name: "Task 13",
    owner: "Mera",
    email: "mera@example.com",
    status: "cancelled",
    priority: "medium",
    description: "Task 13 description",
    due_date: new Date(Date.now() + 12 * 86400000),
    assignees: pickRandomUser()._id,
    price: 1300,
    completion_percentage: 0.3,
    url: "https://www.google.com/search?q=Task+13",
    done: false,
    phone: "+1-555-123-4582",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "14",
    name: "Task 14",
    owner: "Victor Stone",
    email: "victor.stone@example.com",
    status: "in_progress",
    priority: "low",
    description: "Task 14 description",
    due_date: new Date(Date.now() + 13 * 86400000),
    assignees: pickRandomUser()._id,
    price: 1500,
    completion_percentage: 0.55,
    url: "https://www.google.com/search?q=Task+14",
    done: false,
    phone: "+1-555-123-4582",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "15",
    name: "Task 15",
    owner: "Silas Stone",
    email: "silas.stone@example.com",
    status: "completed",
    priority: "high",
    description: "Task 15 description",
    due_date: new Date(Date.now() + 14 * 86400000),
    assignees: pickRandomUser()._id,
    price: 1400,
    completion_percentage: 1.0,
    url: "https://www.google.com/search?q=Task+15",
    done: false,
    phone: "+1-555-123-4582",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  ...generateRandomTasks(300),
];
