// Generated by the renderer in the workspace: every module's
// `app/config/shortcuts-registry.ts`, spread in priority order.
declare module "#shortcuts-aggregated" {
  import type { ComponentShortcuts } from "#dms-ui/app/types/shortcuts";

  const aggregatedShortcuts: ComponentShortcuts[];
  export default aggregatedShortcuts;
}
