export const TableViewEvents = {
  ROW_CLICK: "DmsComponent.TableView.RowClick",
  ROW_CLICK_SUCCESS: "DmsComponent.TableView.RowClickSuccess",
  ROW_CLICK_ERROR: "DmsComponent.TableView.RowClickError",
  ROW_SELECT: "DmsComponent.TableView.RowSelect",
  ROW_DELETE: "DmsComponent.TableView.RowDelete",
  ROW_DELETE_SUCCESS: "DmsComponent.TableView.RowDeleteSuccess",
  ROW_DELETE_ERROR: "DmsComponent.TableView.RowDeleteError",
  ROW_ADD: "DmsComponent.TableView.RowAdd",
  ROW_ADD_SUCCESS: "DmsComponent.TableView.RowAddSuccess",
  ROW_ADD_ERROR: "DmsComponent.TableView.RowAddError",
  ROW_EDIT: "DmsComponent.TableView.RowEdit",
  ROW_EDIT_SUCCESS: "DmsComponent.TableView.RowEditSuccess",
  ROW_EDIT_ERROR: "DmsComponent.TableView.RowEditError",
  ROW_DUPLICATE: "DmsComponent.TableView.RowDuplicate",
  ROW_DUPLICATE_SUCCESS: "DmsComponent.TableView.RowDuplicateSuccess",
  ROW_DUPLICATE_ERROR: "DmsComponent.TableView.RowDuplicateError",
  FILTER_CHANGE: "DmsComponent.TableView.FilterChange",
  SORT_CHANGE: "DmsComponent.TableView.SortChange",
  EXPORT: "DmsComponent.TableView.Export",
  EXPORT_SUCCESS: "DmsComponent.TableView.ExportSuccess",
  EXPORT_ERROR: "DmsComponent.TableView.ExportError",
} as const;
